// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sSBkTIpS-ZLU6qWRwOVGwH_S-Za6vSA',
    appId: '1:43722331780:web:13130138d554b5367914d1',
    messagingSenderId: '43722331780',
    projectId: 'desportivos2026',
    authDomain: 'desportivos2026.firebaseapp.com',
    storageBucket: 'desportivos2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS5Gu5xGCg2h0-i2m-D-yxQ3mCvnI25cA',
    appId: '1:43722331780:android:aafa33bc372d20797914d1',
    messagingSenderId: '43722331780',
    projectId: 'desportivos2026',
    storageBucket: 'desportivos2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsYOrf__1rjgChGKfX5x9oUIGAxb6X7w',
    appId: '1:43722331780:ios:1711dd90ca6f13a37914d1',
    messagingSenderId: '43722331780',
    projectId: 'desportivos2026',
    storageBucket: 'desportivos2026.firebasestorage.app',
    androidClientId: '43722331780-3vd2mq1t5j2nhmeorti3183d10g2u72u.apps.googleusercontent.com',
    iosClientId: '43722331780-nmoh2tvl8gtbereskm9jk1uvokmfugra.apps.googleusercontent.com',
    iosBundleId: 'com.example.despo',
  );
}
